### ISSUE TITLE
code on customer GPU cluster available?

### ISSUE THREAD

**Issue by Irismoon** [snel-repo/autolfads#1]
Hi the authoers,

Thanks for your contribution.
I'm excited to apply this tool to calcium signals. However, I have to use the custom GPU in our lab. Do you have a version of code for that case?
Thank you!

Best,
Mango

**Comment by dbasrai** [comment]
Hi there,

Adding code for using autoLFADS on a local GPU cluster is something we'd like to do, but will take some time and is likely at least several months off from being ready. 

Thanks!
