### ISSUE TITLE
Running the code on local servers

### ISSUE THREAD

**Issue by mafrasiabi** [snel-repo/autolfads#2]
Hi there,

Thanks for sharing this amazing tool. I was wondering if you are going to publish the code that could be run on local GPU servers?

Thanks,
Mohsen

**Comment by dbasrai** [comment]
Hi there,

Publishing code for using autoLFADS on a local GPU cluster is something we'd like to do, but will take some time and is likely at least several months off from being ready.

Thanks!

**Comment by Gunnar-Stunnar** [comment]
Hi everyone!

Just following up if this has been complete? My university has their own cluster and it would be nice to not have to pay for GCP.

cheers

**Comment by cpandar** [comment]
Hi thanks Gunnar. We recently released a [new software package](https://github.com/TNEL-UCSD/autolfads-deploy) and [accompanying paper](https://github.com/TNEL-UCSD/autolfads-deploy/blob/master/paper/paper.pdf), which outlines a few different on-prem and cloud deployment options. Take a look and see if this could work for you!
